[package]
name = "bernoulli-survival"
version = "0.1.0"
authors = ["fuglede", "japanuspus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["dylib"]

[dependencies]
libc = "0.2"
itertools = ""